# Generated by Django 4.1 on 2024-02-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendancedate', models.DateTimeField()),
                ('Employeeno', models.IntegerField()),
                ('Employeename', models.CharField(blank=True, max_length=100, null=True)),
                ('Teamname', models.CharField(blank=True, max_length=100, null=True)),
                ('Sapid', models.CharField(blank=True, max_length=50, null=True)),
                ('Shift', models.CharField(blank=True, max_length=100, null=True)),
                ('Tlname', models.CharField(blank=True, max_length=100, null=True)),
                ('Tlmail', models.CharField(blank=True, max_length=100, null=True)),
                ('worktype', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'AttendanceTracker',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Login',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('Employeeno', models.IntegerField(primary_key=True, serialize=False)),
                ('Employeename', models.CharField(blank=True, max_length=100, null=True)),
                ('Teamname', models.CharField(blank=True, max_length=100, null=True)),
                ('Sapid', models.CharField(blank=True, max_length=50, null=True)),
                ('Shift', models.CharField(blank=True, max_length=100, null=True)),
                ('Tlname', models.CharField(blank=True, max_length=100, null=True)),
                ('Tlmail', models.CharField(blank=True, max_length=100, null=True)),
                ('test', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'TeamDetails',
            },
        ),
        migrations.CreateModel(
            name='workon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worktype', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'WorkType',
            },
        ),
        migrations.AddConstraint(
            model_name='dailyattendance',
            constraint=models.UniqueConstraint(fields=('attendancedate', 'Employeeno'), name='unique_attendance'),
        ),
    ]
