# Generated by Django 4.1 on 2024-02-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_tlmail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='test',
        ),
    ]
