# Generated by Django 4.1 on 2024-02-18 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_remove_team_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTimings',
            fields=[
                ('shifttiming', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='Shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.shifttimings'),
        ),
    ]
