# Generated by Django 4.1 on 2024-02-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_shifttimings_alter_team_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
