# Generated by Django 4.1 on 2024-03-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_teamnamedetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamnamedetail',
            options={},
        ),
    ]
