# Generated by Django 4.1 on 2024-03-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_alter_teamnamedetail_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='testmodel',
            fields=[
                ('testname', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
