# Generated by Django 4.1 on 2024-03-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='testname2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
