# Generated by Django 4.1 on 2024-03-16 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_testmodel_testname2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testmodel',
        ),
        migrations.AlterModelOptions(
            name='teamnamedetail',
            options={'verbose_name_plural': 'teamname'},
        ),
        migrations.AlterField(
            model_name='team',
            name='Teamname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.teamnamedetail'),
        ),
    ]
